apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: db-namespace
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: mydb
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: app-namespace
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: admin123

